name: Build package and run test matrix

env:
  BUILD_PYTHON_VERSION: "3.7"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build packages
        run: |
          python -m build
          shasum dist/*
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  test:
    needs: build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install built packages
        run: |
          pip install -U dist/*.whl
      - name: Test with pytest
        run: |
          pytest --verbose
